require 'net/http'
class WelcomeController < ApplicationController
  def index
  end

  def review
    receipt = params["receipt"]
    # Check Receipt
    uri = URI("https://bitshares.cloudcoin.global/get_receipt.aspx")
    res = Net::HTTP.post_form(uri, "rn" => receipt, 
      "pk" => "E5E56C0D-6792-469E-B7A6-30F9E3F715C9")
    
    # res.code should be 200
    
    if (res.is_a?(Net::HTTPSuccess))
      # if the receipt number and response are correct
      # convert the response into JSON object
      response_json = JSON.parse(res.body)
      # get the status of the receipt
      status = response_json["status"]
      # flash.now[:notice] = response_json.inspect
      if (status == "fail")
        redirect_to welcome_index_url, alert: response_json["message"]
      else
        @receipt_id = response_json["receipt_id"]
        @checked_at = response_json["time"]
        @total_authentic = response_json["total_authentic"]
        @total_fracked = response_json["total_fracked"]
        @total_counterfeit = response_json["total_counterfeit"]
        @total_lost = response_json["total_lost"]
        @coins = response_json["receipt"]
      end
    else
      redirect_to welcome_index_url, alert: "Something went wrong while checking the receipt. Please try again."
      return
    end
  end

  def upload
    uploaded_io = params["cloud_coin_file"]
    if uploaded_io == nil || uploaded_io == ""
      redirect_to welcome_index_url, alert: "Stack file is missing. Please try again."
      return
    end
    # Generate a file name that will be unique YYYYMMSSuploadedfile.stack
    # Eg. 20180616CloudCoins.stack
    generated_file_name = Time.now.strftime("%Y%m%d%H%M%S") + uploaded_io.original_filename
    # Save the uploaded file to public/uploads
    File.open(Rails.root.join('public', 'uploads', generated_file_name), 'wb') do |file|
      file.write(uploaded_io.read)
    end
    
    # Get the file content
    uploaded_file_content = File.read(Rails.root.join('public', 'uploads', generated_file_name))

    # This will hold the receipt generated by Deposit one stack
    receipt = ""

    # https://ruby-doc.org/stdlib-2.5.1/libdoc/net/http/rdoc/Net/HTTP.html
    # http://www.rubyinside.com/nethttp-cheat-sheet-2940.html
    uri = URI.parse("https://bitshares.cloudcoin.global/deposit_one_stack.aspx")
    # Response
    res = ""
    Net::HTTP.start(uri.host, uri.port, :use_ssl => true) do |http|
      req = Net::HTTP::Post.new(uri)
      req.set_form_data("stack" => uploaded_file_content)
      res = http.request(req)
      # res.code should be 200
    end


    if (res.is_a?(Net::HTTPSuccess))
      # if cloudcoin deposit one stack service was able to
      # process the request
      response_json = JSON.parse(res.body)
      # get the status
      status = response_json["status"]
      if (status == "error")
        # real error message is response_json["message"]
        redirect_to welcome_index_url, notice: "Uploaded file is not a valid stack file or there was an unknown error. Please try again."
        return
      end
      receipt = response_json["receipt"]
      redirect_to controller: "welcome", action: "review", file_name: generated_file_name, receipt: receipt
    else
      # if uploaded file is NOT a cloudcoin stack file
      redirect_to welcome_index_url, alert: "Uploaded file is not a valid stack file or there was an unknown error. Please try again."
    end
  end
end
